#!/bin/sh

# script uses named parameters
# ex:
# del --port 8503 --key 332244
#  'key' - hex encoded string

port=${port:-8403}
key=${key:-aabbcc}
tab=${tab:-test}
hostname=${hostname:-`hostname`}

while [ $# -gt 0 ]; do

  if [[ $1 == *"--"* ]]; then
    param="${1/--/}"
    declare $param="$2"
  fi

  shift
done

curl -X POST \
	-H "Content-Type: application/json" \
	-d '{"tab":"'$tab'","key":"'$key'"}' \
	http://$hostname:$port/db/del
