#!/bin/sh

# script uses named parameters
# ex:
# get --port 8503 --key 332244
#  'key' - hex encoded string

port=${port:-8403}
key=${key:-aabbcc}
tab=${tab:-test}
hostname=${hostname:-`hostname`}
opts=${opts:-}
hex=${hex:-false}

while [ $# -gt 0 ]; do

  if [[ $1 == *"--"* ]]; then
    param="${1/--/}"
    declare $param="$2"
  fi

  shift
done

curl "$opts" "http://$hostname:$port/db/get?tab=$tab&key=$key&hex=$hex"
