#!/bin/sh

# script uses named parameters
# ex:
# join --addrs "127.0.0.1:8400"

port=${port:-8403}
addrs=${addrs:-}
hostname=${hostname:-`hostname`}

while [ $# -gt 0 ]; do

   if [[ $1 == *"--"* ]]; then
        param="${1/--/}"
        declare $param="$2"
   fi

  shift
done

curl -v -X POST \
	-H "Content-Type: application/json" \
	-d '{"addrs": "'$addrs'"}' \
        http://$hostname:$port/cluster/join
