#!/bin/sh

# script uses named parameters
# ex:
# put --key 332244 --val 112233
#  'key' and 'val'- hex encoded string

port=${port:-8403}
key=${key:-aabbcc}
val=${val:-00112233}
tab=${tab:-test}
hostname=${hostname:-`hostname`}

while [ $# -gt 0 ]; do

   if [[ $1 == *"--"* ]]; then
        param="${1/--/}"
        declare $param="$2"
   fi

  shift
done

curl -v -X POST \
	-H "Content-Type: application/json" \
	-d '{"tab": "'$tab'","key":"'$key'","val":"'$val'"}' \
        http://$hostname:$port/db/put

