#!/bin/sh

# script uses named parameters
# ex:
# --log debug --hostname localhost

joins=${joins:-127.0.0.1:8400,127.0.0.1:8500}
log=${log:-info}
logfile=${logfile:-}
hostname=${hostname:-}

while [ $# -gt 0 ]; do

  if [[ $1 == *"--"* ]]; then
    param="${1/--/}"
    declare $param="$2"
  fi

  shift
done

./rkvd --db map \
       --data-dir /tmp/rkv/3 \
       --log-level $log \
       --log-file "$logfile" \
       --discovery-addr "$hostname:8600" \
       --discovery-join-addrs $joins \
       --node-name "n3" \
       --raft-port 8601 \
       --rpc-port 8602 \
       --http-addr "$hostname:8603"
