#!/bin/sh

# first node of 'clean cluster' starts without 'discovery-join-addrs'

# script uses named parameters
# ex:
# --log debug --hostname localhost

log=${log:-info}
logfile=${logfile:-}
hostname=${hostname:-}

while [ $# -gt 0 ]; do

  if [[ $1 == *"--"* ]]; then
    param="${1/--/}"
    declare $param="$2"
  fi

  shift
done


./rkvd --db map \
       --data-dir /tmp/rkv/1 \
       --log-level "$log" \
       --log-file "$logfile" \
       --discovery-addr "$hostname:8400" \
       --node-name "n1" \
       --raft-port 8401 \
       --rpc-port 8402 \
       --http-addr "$hostname:8403"
