#!/bin/sh

# script uses named parameters
# ex:
# --log debug --hostname localhost

joins=${joins:-127.0.0.1:8400}
log=${log:-info}
hostname=${hostname:-}

while [ $# -gt 0 ]; do

  if [[ $1 == *"--"* ]]; then
    param="${1/--/}"
    declare $param="$2"
  fi

  shift
done

./rkvd --db map \
       --data-dir /tmp/rkv/2 \
       --log-level $log \
       --discovery-addr "$hostname:8500" \
       --discovery-join-addrs $joins \
       --node-name "n2" \
       --raft-port 8501 \
       --rpc-port 8502 \
       --http-addr "$hostname:8503"
